### PR TITLE
Fix/simple accordion tabindex

### LINKED ISSUE #2147: Accordion collapsibles of the simple variant are not in the tab order
Accordion collapsibles of the simple variant are not in the tab order

_Originally posted by @jrbarnes9 in https://github.com/ONSdigital/design-system/discussions/1377#discussioncomment-2629401_

### PR DESCRIPTION
**Pull request by boxadesign**
### What is the context of this PR?
Fixes #2147 

Also adds tests in the collapsible script tests to cover the scenario when the collapsible is and accordion and when the collapsible is an accordion and the simple variant.

### How to review
Review code and check tests

### CODE REVIEW

File: src/components/collapsible/collapsible.js [hunk 1]
```diff
@@ -29,7 +30,7 @@ export default class Collapsible {
     this.collapsibleHeader.setAttribute('role', 'link');
     this.collapsibleHeader.setAttribute('aria-controls', collapsibleId);
 
-    if (!this.isAccordion) {
+    if (!this.isAccordion || (this.isAccordion && this.isSimpleAccordion)) {
```
Comment (kruncher) [inline src/components/collapsible/collapsible.js:33]: This could be simplified to:
```javascript
if (!this.isAccordion || this.isSimpleAccordion) {
```

Comment (kruncher) [reply src/components/collapsible/collapsible.js:33]: `this.isAccordion` has to be true if it wasn't false.

**Review by kruncher — APPROVED** [review]

**Review by jrbarnes9 — APPROVED** [review]
